name: build-sdl2

on:
  push:
    branches:
      - 'main'
      - 'release/**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  build-windows:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        architecture: [ x64, x86 ]
        os: [ windows ]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: .\scripts\build-sdl2.cmd
      shell: cmd
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}_${{ matrix.architecture }}
        path: .\artifacts\pkg\**\*
        if-no-files-found: error
  build-linux:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        architecture: [ x64 ]
        os: [ ubuntu ]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: ./scripts/build-sdl2.sh
      shell: cmd
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}_${{ matrix.architecture }}
        path: .\artifacts\pkg\**\*
        if-no-files-found: error
