name: update-sdl2

on:
  schedule:
    - cron:  '2 4 * * *'
  workflow_dispatch:

jobs:
  update-sdl2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: .\scripts\update-sdl2.cmd
      shell: cmd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
